### PR TITLE
French Translation : initial commit

### PR DESCRIPTION
**Pull request by chuugar**

### CODE REVIEW

**Comment by gnome17** [comment]
Hi,
thank you for your work on a french translation we would really love to merge this pull request but there are some changes you have to make at first.

Please add to your file only the necessary strings. Your file shouldn't contain strings with the TAG translatable="false". Please take a look to our german translation for an example how this file should look like (https://github.com/gateship-one/malp/blob/HEAD/app/src/main/res/values-de/strings.xml).

**Comment by chuugar** [comment]
Is this OK ?

**Comment by djselbeck** [comment]
Looks very good. Thanks a lot for your effort. I will merge this and you to the authors list. Do you wish to appear with the fullname "Guy de Mölkky" or just the nickname?

**Comment by chuugar** [comment]
Guy de Mölkky is fine, it's already a nickname. Thanks, I'll do Odyssey's translation in my next free time.

**Pull request merged**
