### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by edawn**
de6c96a is useful for testing and
3a80a9c reduces release build size by about 30% and removes logging, as per https://developer.android.com/studio/publish/preparing.html#publishing-configure

### CODE REVIEW

**Comment by djselbeck** [comment]
The application crashes with minify enabled:

`01-13 15:47:46.436 10037 10037 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setOnQueryTextListener(android.support.v7.widget.SearchView$c)' on a null object reference
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at org.gateshipone.malp.application.c.a.g.a(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v4.b.l.b(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v4.b.r.a(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v4.b.o.a(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v4.b.m.onCreatePanelMenu(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v7.view.i.onCreatePanelMenu(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v7.a.i$b.onCreatePanelMenu(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v7.view.i.onCreatePanelMenu(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v7.a.v.j(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.support.v7.a.v$1.run(Unknown Source)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:616)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6223)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-13 15:47:46.436 10037 10037 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
`

**Comment by edawn** [comment]
That's strange, cause the line
-keep class android.support.v7.widget.SearchView { *; }
in app/proguard-rules.pro should prevent that problem

**Comment by djselbeck** [comment]
Thats because I inserted it afterwards ;)

**Comment by djselbeck** [comment]
Deprecated

**Pull request closed without merging**
